export const GET_BOOKLIST_DATA = 'GET_BOOKLIST_DATA';
export const GET_BOOKLIST_DATA_RECIEVED = 'GET_BOOKLIST_DATA_RECIEVED';
export const LOAD_DEFAULT_BOOKLIST_DATA = 'LOAD_DEFAULT_BOOKLIST_DATA';
export const DEFAULT_BOOKLIST_DATA_RECIEVED = 'DEFAULT_BOOKLIST_DATA_RECIEVED';
export const LOGGEDIN = 'LOGGEDIN';
export const NOTLOGGEDIN = 'NOTLOGGEDIN';
export const EMAIL_CHANGED = 'EMAIL_CHANGED'
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL'
export const LOGIN_USER_SUCESS = 'LOGIN_USER_SUCESS'
export const FORGOT = 'FORGOT'

export const UPDATE_TITLE = 'UPDATE_TITLE';
export const UPDATE_AUTHOR = 'UPDATE_AUTHOR';
export const UPDATE_GENRE = 'UPDATE_GENRE';
export const UPDATE_PREFERENCES_FIREBASE= 'UPDATE_PREFERENCES_FIREBASE';

export const BOOK_SAVED_SUCESSFULLY = 'BOOK_SAVED_SUCESSFULLY';
export const BOOK_NOT_SAVED = 'BOOK_NOT_SAVED';



