export const GET_BOOKLIST_DATA = 'GET_BOOKLIST_DATA';
export const GET_BOOKLIST_DATA_RECIEVED = 'GET_BOOKLIST_DATA_RECIEVED';
export const LOGGEDIN = 'LOGGEDIN';
export const NOTLOGGEDIN = 'NOTLOGGEDIN';
export const EMAIL_CHANGED = 'EMAIL_CHANGED'
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL'
export const LOGIN_USER_SUCESS = 'LOGIN_USER_SUCESS'
export const FORGOT = 'FORGOT'

