export const BOOK_SUGGESTIONS_DATA_RECIEVED = 'BOOK_SUGGESTIONS_DATA_RECIEVED';
export const LOGGEDIN = 'LOGGEDIN';
export const NOTLOGGEDIN = 'NOTLOGGEDIN';
export const EMAIL_CHANGED = 'EMAIL_CHANGED'
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL'
export const LOGIN_USER_SUCESS = 'LOGIN_USER_SUCESS'
export const FORGOT = 'FORGOT'
export const PASSWORD_CONFIRM = 'PASSWORD_CONFIRM'
export const CLEARFORM = 'CLEARFORM';

export const BOOK_SAVED = 'BOOK_SAVED';
export const BOOK_NOT_SAVED = 'BOOK_NOT_SAVED';
export const BOOK_SEARCH = 'BOOK_SEARCH'
export const CHANGE_SEARCH = 'CHANGE_SEARCH'
export const LOAD_SAVED_BOOKS = 'LOAD_SAVED_BOOKS'
export const BOOK_SEARCH_CLEAR = 'BOOK_SEARCH_CLEAR'

export const FETCHED_BOOKS = 'export const'
export const SEARCH_TYPE = ' SEARCH_TYPE'
export const GET_SAVED_BOOK = 'GET_SAVED_BOOK'
export const CLEAR_BOOKS = 'ClEAR_BOOKS'

export const UPDATE_QUERY= 'UPDATE_QUERY'
export const UPDATE_FRIEND_STATUS = 'UPDATE_FRIEND_STATUS'
export const UPDATE_SEARCH_RESULT ='UPDATE_SEARCH_RESULT'
export const UPDATE_DISPLAY = 'UPDATE_DISPLAY'

export const  UPDATE_SUGGESTIONS ='UPDATE_SUGGESTIONS'
export const  HAS_SUGGESTIONS = ' HAS_SUGGESTIONS';

export const UPDATE_PREFERENCE_TYPE ='UPDATE_PREFERENCE_TYPE';
export const UPDATE_PREFERENCE_KEYWORD ='UPDATE_PREFERENCE_KEYWORD';

export const TOGGLE_CAMERAROLL = 'TOGGLE_CAMERAROLL'

export const READ = 'READ'
export const LOADING= 'LOADING'

export const UPDATE_TYPE_ERROR= 'UPDATE_TYPE_ERROR'
export const UPDATE_VALUE_ERROR= 'UPDATE_VALUE_ERROR'